apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  labels:
    {{- include "podiumd-minikube.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "vendor/dimpact-zaakafhandelcomponent/keycloak/*.json").AsConfig | nindent 2 }}
