{{- if .Values.podiumd.openformulieren.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openformulieren-create-superuser-script
  labels:
    {{- include "podiumd-minikube.labels" . | nindent 4 }}
data:
  create_superuser.py: {{ .Files.Get "vendor/dimpact-zaakafhandelcomponent/openformulieren/create_superuser.py" | quote }}
{{- end }}
