apiVersion: v1
kind: ConfigMap
metadata:
  name: openzaak-no2fa-settings
  labels:
    {{- include "podiumd-minikube.labels" . | nindent 4 }}
data:
  docker_no2fa.py: {{ .Files.Get "vendor/dimpact-zaakafhandelcomponent/openzaak/docker_no2fa.py" | quote }}
