apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solr
  labels:
    {{- include "podiumd-minikube.labels" . | nindent 4 }}
spec:
  ingressClassName: traefik
  rules:
    - host: solr.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: solr
                port:
                  name: solr
