apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr
  labels:
    {{- include "podiumd-minikube.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
