apiVersion: v1
kind: Service
metadata:
  name: solr
  labels:
    {{- include "podiumd-minikube.labels" . | nindent 4 }}
spec:
  selector:
    app: solr
  ports:
    - name: solr
      port: 8983
      targetPort: solr
