apiVersion: v1
kind: Service
metadata:
  name: wiremock
  labels:
    {{- include "podiumd-minikube.labels" . | nindent 4 }}
spec:
  selector:
    app: wiremock
  ports:
    - name: http
      port: 8080
      targetPort: http
